kind: pipeline
type: docker
name: Chrome
workspace:
  base: /srv/chrome
  path: .

steps:
  - name: run
    image: python3.8
    commands:
      - pwd
      - ls
      - pip install -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt