kind: pipeline
name: default
steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: Tinger/chrome
      use_cache: true
      username:
        from_secret: Tinger
      password:
        from_secret: passwd
    tags:
      - latest
when:
  event: push
  branch: master