kind: pipeline
type: docker
name: chrome

steps:
  - name: republish
    image: plugins/docker
    settings:
      repo: Tinger/Chrome
      secrets: [docker-user, docker-passwd]
      tages: latest
    commands:
      - docker images
      - docker ps
      - docker ps -a
      - docker build -t chrome:latest .
      - docker run -d --name Chrome -p 127.0.0.1:5000:5000 chrome:latest