kind: pipeline
name: Chrome
workspace:
  base: /chrome
  path: .

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: redreg.redhome.cc/test
      registry: redreg.redhome.cc
      username: drone
      password: dronelogin
      mirror: https://fhvwls99.mirror.aliyuncs.com
      debug: true
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
    when:
      branch:
        - master

  - name: update-service
    image: redhome/docker-cli
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker login redreg.redhome.cc --username drone --password dronelogin
      - docker pull redreg.redhome.cc/test:${DRONE_COMMIT_SHA:0:8}
      - docker ps -a
    when:
      branch:
        - master

volumes:
  - name: docker
    path: /var/run/docker.sock

trigger:
  branch:
    - master