kind: pipeline
type: docker
name: chrome

steps:
  - name: republish
    image: plugins/docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker ps -a
      - docker build -t chrome:latest .
      - docker run -d --name Chrome -p 127.0.0.1:5000:5000 chrome:latest
    when:
      branch:
        - master

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master
  event:
    - push