kind: pipeline
type: docker
name: chrome

steps:
  - name: republish
    image: plugins/docker
    settings:
      repo: Tinger/Chrome
      secrets: [docker-user, docker-passwd]
      tages: latest
    commands:
      - docker-compose up -d