kind: pipeline
type: docker
name: chrome

workspace:
  path: /srv/Dockers/chrome

steps:
  - name: republish
    image: plugins/docker
    settings:
      repo: Tinger/Chrome
      secrets: [docker-user, docker-passwd]
      tages: latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - pwd
      - ls
      - docker ps -a

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
#    commands:
#      - docker build -t chrome:latest .
#      - docker run -d --name Chrome -p 127.0.0.1:5000:5000 chrome:latest

trigger:
  branch:
    - master
  event:
    - push