version: '3'

services:
  Chrome:
    build: .
    image: chrome:latest
    container_name: Chrome
    restart: always
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - /srv/Dockers/chrome/:/srv/Chrome/
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock